### ISSUE TITLE
ensure the template is using latest version

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk-minimal-template#1]
the template should be using the latest release version, or at very minimal, only 1 major version behind

**Comment by rzadp** [comment]
For sure, the goal is to update the templates after every release (to `crates.io`).

Currently the templates are not updated because we've run into some issues - the work can be tracked [here](https://github.com/paritytech/eng-automation/issues/6).

**Comment by rzadp** [comment]
All three templates are now being kept up to date - most recently, with version `1.13.0`.
