### ISSUE TITLE
undeclared modules in pallets

### ISSUE THREAD

**Issue by DarkArtistry** [paritytech/polkadot-sdk-minimal-template#12]
Hi,

Have anyone tested clicking on "use this template" and then running the `cargo build --package minimal-template-node --release` ?

Below is the screenshot of the user experience.

![image](https://github.com/user-attachments/assets/3206c17b-18e3-4a2d-ae0e-53f9c5a5b06c).

First command, and it fails.

May i suggestion a CICD checker service ?

**Comment by rzadp** [comment]
Hello,

The repo does have CICD checks:

<img width="620px" src="https://github.com/user-attachments/assets/1a9c93a8-d260-4c93-bcd5-785169ab886c">

I just checked and it works for me locally too.

What is your rust compiler version? Perhaps there is something there.

**Comment by DarkArtistry** [comment]
Hi,

My rust compiler version:
➜ rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29)


my rust active tools:
➜ rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/zhenhaowu/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-2022-09-14-aarch64-apple-darwin
nightly-2022-11-14-aarch64-apple-darwin
nightly-2022-12-10-aarch64-apple-darwin
nightly-2023-05-22-aarch64-apple-darwin
nightly-2024-02-16-aarch64-apple-darwin
nightly-2024-04-22-aarch64-apple-darwin
nightly-aarch64-apple-darwin
1.70-aarch64-apple-darwin
1.74-aarch64-apple-darwin
1.75-aarch64-apple-darwin
1.76-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.78.0 (9b00956e5 2024-04-29)


I had a friend try the procedure, "use this template" followed by the build command, we both have the same error.

**Comment by rzadp** [comment]
@DarkArtistry The issue has been corrected. There actually was a difference between the `cargo build --package minimal-template-node --release` command from the readme and the `cargo build --release` command.

Sorry about your bad experience.
